// app/page.tsx
import Link from 'next/link';
import { Metadata } from 'next';
import { getAllPublished } from '@/lib/notion';
import { ThemeToggle } from '@/components/theme-toggle';

// Types
interface BlogPost {
  slug: string;
  title: string;
  date: string;
  description: string;
}

// Metadata
export const metadata: Metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
};

// Main component
export default async function Home() {
  const posts = await getAllPublished();

  if (!posts || posts.length === 0) {
    return <h1 className="text-2xl font-bold p-4">No posts</h1>;
  }

  return (
    <div className="min-h-screen p-4">
      <main className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-8 text-black dark:text-white">Blog <ThemeToggle /></h1>
        
        {posts.map((post: BlogPost) => (
          <section key={post.slug} className="mb-8 p-4 border rounded-lg hover:shadow-lg transition-shadow">
            <div className="mb-4">
              <h2 className="text-2xl font-semibold mb-2">
                <Link 
                  href={`/posts/${post.slug}`}
                  className="hover:text-blue-600 text-black dark:text-white transition-colors"
                >
                  {post.title}
                </Link>
              </h2>
              <div className="text-gray-600">
                {post.date}
              </div>
            </div>
            <p className="text-gray-700">
              {post.description}
            </p>
          </section>
        ))}
      </main>
    </div>
  );
}